### ISSUE TITLE
Problems with IQ_bullet_list on IQdesktop 1.3.1

### ISSUE THREAD

**Issue by dkaschek** [IntiQuan/IQSlides#2]
Many of you have come across problems with IQSlides on IQdesktop 1.3.1, including myself.

IQSlides relies on the `officer` package. It seems that they have changed the way how formatted text can be written to PPTX. That affects especially the `IQ_bullet_list` function.

Quick workaround for now:

Get `officer 0.3.5` from here: [https://cran.r-project.org/src/contrib/Archive/officer/]
Get `flextable 0.5.5` from here: [https://cran.r-project.org/src/contrib/Archive/flextable/]

Install the packages from the command line (bash):

`R CMD INSTALL flextable_0.5.5.tar.gz`
`R CMD INSTALL officer_0.3.5.tar.gz`

I will have a closer look when I find the time.

**Comment by adrianhauber** [comment]
The issue was probably due to depreciation of the officer function `ph_add_text`. It could be resolved by changing the code that interprets bullet lists to use `block_list` together with `ph_with` instead, which supports advanced formatting options in `officer 0.3.14` and above. The updated packages for `officer` (& `zip`, `webshot`, `flextable`), as well as the mentioned changes in the code, are included in `IQslides 0.3.0`, which is available within `IQdesktop 1.3.2`.
